version: "3.9"

services:
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE${DB_NAME}
      - TZ=${TZ}
    volumes:
      - mysqlvol1:/var/lib/mysql
volumes:
  mysqlvol1:
